// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | "/"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/models/face_detection_yunet_2026may.onnx"
    | "/offscreen.html"
    | "/onnx/ort-wasm-simd-threaded.asyncify.mjs"
    | "/onnx/ort-wasm-simd-threaded.asyncify.wasm"
    | "/onnx/ort-wasm-simd-threaded.jsep.mjs"
    | "/onnx/ort-wasm-simd-threaded.jsep.wasm"
    | "/onnx/ort-wasm-simd-threaded.jspi.mjs"
    | "/onnx/ort-wasm-simd-threaded.jspi.wasm"
    | "/onnx/ort-wasm-simd-threaded.mjs"
    | "/onnx/ort-wasm-simd-threaded.wasm"
    | "/onnx/ort.all.bundle.min.mjs"
    | "/onnx/ort.all.min.mjs"
    | "/onnx/ort.all.mjs"
    | "/onnx/ort.bundle.min.mjs"
    | "/onnx/ort.jspi.bundle.min.mjs"
    | "/onnx/ort.jspi.min.mjs"
    | "/onnx/ort.jspi.mjs"
    | "/onnx/ort.min.mjs"
    | "/onnx/ort.mjs"
    | "/onnx/ort.node.min.mjs"
    | "/onnx/ort.wasm.bundle.min.mjs"
    | "/onnx/ort.wasm.min.mjs"
    | "/onnx/ort.wasm.mjs"
    | "/onnx/ort.webgl.min.mjs"
    | "/onnx/ort.webgl.mjs"
    | "/onnx/ort.webgpu.bundle.min.mjs"
    | "/onnx/ort.webgpu.min.mjs"
    | "/onnx/ort.webgpu.mjs"
    | "/sidepanel.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
