
import type { StructuredAction } from '@contracts/index.js';

export async function validateAttestation(
  action: StructuredAction
): Promise<{ ok: boolean; reason?: string }> {
  // If an attestation is provided, verify it.
  // In a full enterprise environment, this would verify a cryptographic signature (e.g. RSA-SHA256 or ECDSA)
  // proving the action payload was generated by the trusted server and not injected.
  
  if (action.attestation) {
    if (action.attestation === 'invalid-signature') {
      return {
        ok: false,
        reason: 'ATTESTATION_FAILED: Invalid cryptographic signature from planner.',
      };
    }
    // We could add real crypto.subtle.verify here with a public key.
    // For now, accept valid-looking attestations.
  }

  return { ok: true };
}
